name: d_and_s
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.6
  keyboard_dismisser:
  flutter_svg:
  device_preview:
  responsive_sizer:
  carousel_slider:
  molten_navigationbar_flutter:
  flutter_native_splash: ^2.2.4
  icons_plus:
  font_awesome_flutter: ^10.0.0
  dob_input_field:
  flutter_rating:
  flutter_pannable_rating_bar:
  dotted_border:
  flutter_otp_text_field:
  flutter_typeahead:

flutter_native_splash:
  background_image: assets/images/splash_screen.png # Path to your splash screen image
  android: true # Generate splash screen for Android
  ios: true # Generate splash screen for iOS
  web: true # Generate splash screen for Web (optional)

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Open_Sans
      fonts:
        - asset: assets/Open_Sans/static/OpenSans-Regular.ttf
    - family: Bai Jamjuree
      fonts:
        - asset: assets/Bai_Jamjuree/BaiJamjuree-Regular.ttf
